name: _lint-check

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: false
        default: '3.11'

jobs:
  check:
    runs-on: ubuntu-latest
    name: "リントチェック"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Lint Check With flake8
        run: |
          pip install flake8
          flake8 \
            --max-line-length 120 \
            --per-file-ignores __init__.py:F401,E402 \
            --statistics
